-- =============================================================================
-- voice_quotes — per-habit marginalia cache (Phase 3).
--
-- Purpose:
--   The Today screen renders a tiny italic literary-serif quote under the
--   "next pending" habit. The quote is generated by the generate_quote Edge
--   Function (Gemini 2.5 Flash) using the user's voice_profile, and cached
--   here for 24h. UNIQUE on (user_id, habit_id) so the Edge Function's upsert
--   refreshes an expired row instead of creating duplicates.
-- =============================================================================

CREATE TABLE public.voice_quotes (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  habit_id     uuid NOT NULL REFERENCES public.habits(id)   ON DELETE CASCADE,
  quote_text   text NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL DEFAULT (now() + interval '24 hours'),
  UNIQUE (user_id, habit_id)
);

CREATE INDEX voice_quotes_user_expires_idx
  ON public.voice_quotes (user_id, expires_at);

ALTER TABLE public.voice_quotes ENABLE ROW LEVEL SECURITY;

CREATE POLICY voice_quotes_select_own ON public.voice_quotes
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY voice_quotes_insert_own ON public.voice_quotes
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY voice_quotes_update_own ON public.voice_quotes
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY voice_quotes_delete_own ON public.voice_quotes
  FOR DELETE USING (auth.uid() = user_id);
